/*
*  .d8888b.           888      888b     d888                   888b    888
* d88P  Y88b          888      8888b   d8888                   8888b   888
* 888    888          888      88888b.d88888                   88888b  888
* 888         8888b.  88888b.  888Y88888P888  8888b.   .d8888b 888Y88b 888
* 888  88888     "88b 888 "88b 888 Y888P 888     "88b d88P"    888 Y88b888
* 888    888 .d888888 888  888 888  Y8P  888 .d888888 888      888  Y88888
* Y88b  d88P 888  888 888 d88P 888   "   888 888  888 Y88b.    888   Y8888
*  "Y8888P88 "Y888888 88888P"  888       888 "Y888888  "Y8888P 888    Y888

* All bugs and glitches proudly made by @GabMacN.

* @GabMacN 2026

* GitHub: GabMacN
* Discord: gabmacn
* Youtube: @GabMacN
* Instagram: @gabmacn

* Path: src/modules/nail/types/llm.rs
* Name: llm.rs
* Description: LLM (Large Language Model) types and structures used within the nail module of the GabMacN ecosystem.
*/

/// Enum representing the type of author for messages in LLM interactions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Role {
  /// Messages generated by the system are held in high regard by the AI, often setting the context or rules for the conversation.
  System,
  /// Messages from the user are the primary input for the AI, guiding its responses and actions.
  User,
  /// Messages from the AI assistant itself, which may include responses, clarifications, or follow-up questions.
  Assistant,
  /// Messages from external tools or plugins that the AI may interact with to gather information or perform actions.
  Tool,
}
